### ISSUE TITLE
Issues with installation

### ISSUE THREAD

**Issue by gtholder1** [Diksta33/PathOfExileClipboardListener#2]
Love the program, but since 1.0.17 release I am unable to install new versions.

I have tried updating an existing installation, and also a clean install of your program but I get the following error message about system.data.sqlite version

![1 0 17](https://f.cloud.github.com/assets/6704167/2184718/15128e0c-97c6-11e3-9248-7a4643b30b61.png)

When I attempt to install 1.0.20 I get the same message, but with a different (newer version of Sqlite identified as needed.

![1 0 20](https://f.cloud.github.com/assets/6704167/2184728/47e34bd2-97c6-11e3-90c4-2b20c6a2a5c2.png)

Earlier versions work fine, though having to rename subsequent downloaded versions back to publish so the install routine will complete is a pain.

It would be great if you could release a new baseline pre-release version that has all needed dependencies and an install routine that doesn't care what directory name the previous version was installed from.

Anyway, Thanks for all your hard work!

G

**Comment by Diksta33** [comment]
Okay, first thing to note is that when you install this you should be double-clicking the "click once" application file and NOT the setup.exe.  A few people have had installation problems that were fixed once they knew this.

I think that what has happened here is probably my fault though.  A little bit of background, I am developing this on three different machines, all running 64-bit Windows 7.  I had a few issues with mixed-mode assemblies and decided I would be safest using the 32-bit SQLite DLL because of this.  I then discovered that this is what I had been using already on my main machine, but my other two environments had the 64-bit version.  So I messed around installing and uninstalling the drivers until all three machines managed to compile and run successfully.

I am going to guess that during this I managed to drop the dependency out of the manifest so that the installation won't include the correct version of the SQLite DLL.  You should be able to workaround this in the short-term by going here: https://system.data.sqlite.org/downloads/1.0.91.0/sqlite-netFx40-setup-bundle-x86-2010-1.0.91.0.exe and installing that package.

I can't do much at the moment as I am at work but the next chance I get I will make sure this is included in the installation package and publish a new version.

I am a bit limited with the options for the installation but I will see if I can find a better way to handle having new installations without so many headaches.

**Comment by Diksta33** [comment]
Okay, I couldn't resist looking at this.  I never read the documentation properly from the SQLite .NET website.  I have followed the instructions there properly now and I noticed that the file included in the installation package is different to the one being included previously.  Hopefully this will solve the problem, let me know if it helps.  I will publish a new release now.

**Comment by gtholder1** [comment]
Looks like the right includes got packaged.  Install works now.  Thanks for fixing that so quickly!
 Any idea on how to fix the whole have to install updates FROM the same directory it was initially installed from?

**Comment by gtholder1** [comment]
sigh oops didnt mean to close it yet... unless you want me to, if so then I'll start another issue about the install routine being picky about where it is being ran from.

**Comment by Diksta33** [comment]
I think if you close this and open another issue it would be for the best.

The fact is that using ClickOnce for deployment doesn't really leave a lot of options.  To allow the install to run from any install path I would have to move away from ClickOnce I think and that isn't likely to happen in the short-term.  Although I wouldn't rule it out as a future change.

http://msdn.microsoft.com/en-us/library/t71a733d%28v=VS.100%29.aspx

**Comment by Diksta33** [comment]
I tried adding an InnoSetup installation package.  if you could try this and let me know if it is any better?

**Comment by Diksta33** [comment]
...and just to warn you, that was a one-off until I know whether it works or not.  So the latest release is back to clickonce.

**Comment by gtholder1** [comment]
The new Install package is definitely the way to go.  Much smoother more user friendly install routine.  Still a little rough around the edges (it has trouble properly closing a running instance of listener to enable a new install).  I will close the current issue and open one on the new installer package for you.
